name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.6.1

      - name: Install dependencies
        run: npm ci

      - name: Set up Environment Variables
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          echo "MONGODB_URI=$MONGODB_URI" >> $GITHUB_ENV

      - name: Run Tests
        run: npm test
