name: Run Tests

on:
  push:
    branches:
      - main # Replace 'main' with the name of your default branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.6.1

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm test
